# This is a basic workflow to help you get started with Actions

name: first-WF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      APP_ENV: Dev
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Build artifact
        run: |
          echo "Hello world, welcom" >> art.txt
          echo "file generated"
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/upload-artifact@v7
        with:
          path: .



      # Runs a single command using the runners shell
      - name: Show Env and pass
        run: echo "Using $APP_ENV and password is $DB_PASSWORD"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    # env:
    #   APP_ENV: Dev
    #   DB_PASSWORD: ${{secrets.DB_PASSWORD}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Test Step
        run: echo "testing all apps"
